movieproject/movieapp/urls.py
from django.urls import path

from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('Movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add,name="add"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=25)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='photo')

def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import Movieform
from . models import Movie
# Create your views here.
def index(request):
    movies=Movie.objects.all()
    context={
        'movie_name':movies
    }
    return render(request,'index.html',context)

def details(request, movie_id):
    movie= Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})

def add(request):
    if request.method=='POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=Movieform(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form style="text-align:center;"     method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="desc" placeholder="enter description"><br>
    <input type="text" name="year" placeholder="enter the year"><br>
    <input type="file" name="img"><br>
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:pink">
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">movies</a>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    <h2> are you want to delete this movie?</h2><br>
    <input type="submit">
</form>

movieproject/templates/details.html
{% extends 'base.html' %}
 {% block body %}
<div class="container">
 <div class="row">
  <div class="col-md-6">
   <img src="{{movie.img.url}}" width="300" height="300">
  </div>
  <div class="col-md-6">
   <h3>{{movie.name}}</h3>
    <h6>{{movie.desc}}</h6>
   <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}"> update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"> delete</a>
  </div>
 </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form style="background-color:grey;text-align:center;" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
<!-- As a link -->
{% extends 'base.html' %}
 {% block body %}
<div class="container" >
 <div class="row">
  {% for i in movie_name %}
  <div class="col-md-3" >
   <div class="card" style="width:100%;height:100%;">
     <img class="card-img-top" src="{{i.img.url}}" width="250px" height="250px" alt="Card image cap">
      <div class="text-center">
      <h5 class="card-title">{{i.name}}</h5>
       <p class="card-text">{{i.desc}}</p>
       <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Go somewhere</a>
       </div>
     </div>
  </div>
  {% endfor %}
 </div>
</div>
{% endblock %}